// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_5COjJAtBTUHkEgb4BHESa4hNHpqr1h0',
    appId: '1:62523843489:web:9f3faad69c0473617321e0',
    messagingSenderId: '62523843489',
    projectId: 'whatsapp-backend-c5712',
    authDomain: 'whatsapp-backend-c5712.firebaseapp.com',
    storageBucket: 'whatsapp-backend-c5712.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ6kuR8meYUpXHSy3p64vFCS1Idn3bxLw',
    appId: '1:62523843489:android:832514b250fd97fa7321e0',
    messagingSenderId: '62523843489',
    projectId: 'whatsapp-backend-c5712',
    storageBucket: 'whatsapp-backend-c5712.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsTkGekxs5u3ShpjgMKVhy3q9LCKruSDc',
    appId: '1:62523843489:ios:db8a396360281be17321e0',
    messagingSenderId: '62523843489',
    projectId: 'whatsapp-backend-c5712',
    storageBucket: 'whatsapp-backend-c5712.appspot.com',
    androidClientId: '62523843489-4me803ikbmot4831rsp1uq84fbt35ec7.apps.googleusercontent.com',
    iosClientId: '62523843489-3aeo6adkskagj8fu859uml0o8ncrh1kv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsTkGekxs5u3ShpjgMKVhy3q9LCKruSDc',
    appId: '1:62523843489:ios:db8a396360281be17321e0',
    messagingSenderId: '62523843489',
    projectId: 'whatsapp-backend-c5712',
    storageBucket: 'whatsapp-backend-c5712.appspot.com',
    androidClientId: '62523843489-4me803ikbmot4831rsp1uq84fbt35ec7.apps.googleusercontent.com',
    iosClientId: '62523843489-3aeo6adkskagj8fu859uml0o8ncrh1kv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTask',
  );
}
